//
// Created by twak on 14/10/2019.
//

#include <iostream>
#include <QApplication>
#include <QtMultimediaWidgets/QVideoWidget>
#include <QMediaPlaylist>
#include <string>
#include <dirent.h>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QHBoxLayout>
#include <QtCore/QFileInfo>
#include <QtWidgets/QFileIconProvider>
#include <QImageReader>
#include "the_player.h"
#include "the_button.h"


using namespace std;

vector<QUrl>* getFilesIn (string loc) {

    vector<QUrl>* out = new vector<QUrl>();
    DIR *dpdf;
    struct dirent *epdf;

    dpdf = opendir(loc.c_str());
    if (dpdf != NULL) {//            printf("Filename: %s",epdf->d_name);

        while (epdf = readdir(dpdf)) {
            if (!epdf->d_name || epdf->d_name[0] == '.')
                continue;

            int l = strlen (epdf -> d_name);

            if ( NULL == strstr (epdf ->d_name, ".png") ) {

//                string s (  epdf->d_name );
//                string root = root + "/" + s.substr(0, s.length() - 4);
//                std::cout << root << std::endl;

            }

            QPushButton *but = new QPushButton();
        }
    }

    return out;
}


// please DO NOT edit this file beyond this line
int main(int argc, char *argv[]) {

    // let's just check that Qt is operational first
    cout << "Qt version: " << QT_VERSION_STR << endl;

    QString fileName = "/home/twak/Downloads/a.MOV";
    // create the Qt Application
    QApplication app(argc, argv);

    vector<QUrl>* videos = getFilesIn ("/home/twak/Videos/cw2");

    ThePlayer* player = new ThePlayer;

//    QMediaPlaylist* playlist = new QMediaPlaylist(player);
//    playlist->addMedia(QUrl::fromLocalFile("/media/twak/data/pics/contour/new phone 2_to_merge/MOV_0022.mp4"));
    player->setMedia(QUrl::fromLocalFile("/home/twak/Downloads/b.MOV"));
//    player->setMedia(QUrl::fromLocalFile("/home/twak/Downloads/e.mp4"));
//    playlist->addMedia(QUrl("file:///media/twak/data/pics/contour/new phone 2_to_merge/MOV_002xx2.mp4"));
//    playlist->addMedia(QUrl("http://example.com/myclip2.mp4"));

    QVideoWidget* videoWidget = new QVideoWidget;
    player->setVideoOutput(videoWidget);

//    videoWidget->show();
    player->setVolume(0); // be slightly less annoying
//    playlist->setCurrentIndex(0);
    player->play();

    QWidget* buttonWidget = new QWidget();
    QHBoxLayout* layout = new QHBoxLayout();
    buttonWidget -> setLayout(layout);

    TheButton* buttons[3];

//    QFileInfo info = QFileInfo("/home/twak/Videos/cw2/a.mp4");
//    QFileIconProvider provider;
//    QIcon icon = provider.icon(info);
//    qDebug()<<"availableSizes: "<<icon.availableSizes();

    QImageReader *imageReader = new QImageReader("/home/twak/Videos/cw2/a.png");
    QImage sprite = imageReader->read();

    for (int i = 0; i < 3; i++) {
        TheButton * button = new TheButton(buttonWidget, videoWidget);
        layout->addWidget(button);
        button -> setIcon(QIcon (":/") );
        buttons[i] = button;

        button -> init (videos->at(i));

        QIcon ico = QIcon(QPixmap::fromImage(sprite));

        button -> setIconSize(QSize(200,200));
        button->setIcon( ico );
    }

    QWidget window;
    QVBoxLayout* hb = new QVBoxLayout();
    hb->setContentsMargins(0,0,0,0);
    window.setLayout(hb);
    window.setFixedSize(800, 540);

    hb -> addWidget(videoWidget);
    hb -> addWidget(buttonWidget);


    window.show();


         // wait for the app to terminate
        return app.exec();
    }
