# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/twak/code/2811_cw2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/twak/code/2811_cw2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/twak/code/2811_cw2/CMakeFiles /home/twak/code/2811_cw2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/twak/code/2811_cw2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cw2

# Build rule for target.
cw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2
.PHONY : cw2

# fast build rule for target.
cw2/fast:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/build
.PHONY : cw2/fast

#=============================================================================
# Target rules for targets named cw2_autogen

# Build rule for target.
cw2_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2_autogen
.PHONY : cw2_autogen

# fast build rule for target.
cw2_autogen/fast:
	$(MAKE) -f CMakeFiles/cw2_autogen.dir/build.make CMakeFiles/cw2_autogen.dir/build
.PHONY : cw2_autogen/fast

cw2_autogen/mocs_compilation.o: cw2_autogen/mocs_compilation.cpp.o

.PHONY : cw2_autogen/mocs_compilation.o

# target to build an object file
cw2_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.o
.PHONY : cw2_autogen/mocs_compilation.cpp.o

cw2_autogen/mocs_compilation.i: cw2_autogen/mocs_compilation.cpp.i

.PHONY : cw2_autogen/mocs_compilation.i

# target to preprocess a source file
cw2_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.i
.PHONY : cw2_autogen/mocs_compilation.cpp.i

cw2_autogen/mocs_compilation.s: cw2_autogen/mocs_compilation.cpp.s

.PHONY : cw2_autogen/mocs_compilation.s

# target to generate assembly for a file
cw2_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.s
.PHONY : cw2_autogen/mocs_compilation.cpp.s

the_button.o: the_button.cpp.o

.PHONY : the_button.o

# target to build an object file
the_button.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.o
.PHONY : the_button.cpp.o

the_button.i: the_button.cpp.i

.PHONY : the_button.i

# target to preprocess a source file
the_button.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.i
.PHONY : the_button.cpp.i

the_button.s: the_button.cpp.s

.PHONY : the_button.s

# target to generate assembly for a file
the_button.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_button.cpp.s
.PHONY : the_button.cpp.s

the_player.o: the_player.cpp.o

.PHONY : the_player.o

# target to build an object file
the_player.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.o
.PHONY : the_player.cpp.o

the_player.i: the_player.cpp.i

.PHONY : the_player.i

# target to preprocess a source file
the_player.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.i
.PHONY : the_player.cpp.i

the_player.s: the_player.cpp.s

.PHONY : the_player.s

# target to generate assembly for a file
the_player.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/the_player.cpp.s
.PHONY : the_player.cpp.s

tomeo.o: tomeo.cpp.o

.PHONY : tomeo.o

# target to build an object file
tomeo.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.o
.PHONY : tomeo.cpp.o

tomeo.i: tomeo.cpp.i

.PHONY : tomeo.i

# target to preprocess a source file
tomeo.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.i
.PHONY : tomeo.cpp.i

tomeo.s: tomeo.cpp.s

.PHONY : tomeo.s

# target to generate assembly for a file
tomeo.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/tomeo.cpp.s
.PHONY : tomeo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cw2"
	@echo "... edit_cache"
	@echo "... cw2_autogen"
	@echo "... cw2_autogen/mocs_compilation.o"
	@echo "... cw2_autogen/mocs_compilation.i"
	@echo "... cw2_autogen/mocs_compilation.s"
	@echo "... the_button.o"
	@echo "... the_button.i"
	@echo "... the_button.s"
	@echo "... the_player.o"
	@echo "... the_player.i"
	@echo "... the_player.s"
	@echo "... tomeo.o"
	@echo "... tomeo.i"
	@echo "... tomeo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

