# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/85/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/85/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/twak/code/cw2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/twak/code/cw2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/85/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/85/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/twak/code/cw2/CMakeFiles /home/twak/code/cw2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/twak/code/cw2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cw2

# Build rule for target.
cw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2
.PHONY : cw2

# fast build rule for target.
cw2/fast:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/build
.PHONY : cw2/fast

#=============================================================================
# Target rules for targets named cw2_autogen

# Build rule for target.
cw2_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cw2_autogen
.PHONY : cw2_autogen

# fast build rule for target.
cw2_autogen/fast:
	$(MAKE) -f CMakeFiles/cw2_autogen.dir/build.make CMakeFiles/cw2_autogen.dir/build
.PHONY : cw2_autogen/fast

cw2_autogen/mocs_compilation.o: cw2_autogen/mocs_compilation.cpp.o

.PHONY : cw2_autogen/mocs_compilation.o

# target to build an object file
cw2_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.o
.PHONY : cw2_autogen/mocs_compilation.cpp.o

cw2_autogen/mocs_compilation.i: cw2_autogen/mocs_compilation.cpp.i

.PHONY : cw2_autogen/mocs_compilation.i

# target to preprocess a source file
cw2_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.i
.PHONY : cw2_autogen/mocs_compilation.cpp.i

cw2_autogen/mocs_compilation.s: cw2_autogen/mocs_compilation.cpp.s

.PHONY : cw2_autogen/mocs_compilation.s

# target to generate assembly for a file
cw2_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/cw2_autogen/mocs_compilation.cpp.s
.PHONY : cw2_autogen/mocs_compilation.cpp.s

responsive_label.o: responsive_label.cpp.o

.PHONY : responsive_label.o

# target to build an object file
responsive_label.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_label.cpp.o
.PHONY : responsive_label.cpp.o

responsive_label.i: responsive_label.cpp.i

.PHONY : responsive_label.i

# target to preprocess a source file
responsive_label.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_label.cpp.i
.PHONY : responsive_label.cpp.i

responsive_label.s: responsive_label.cpp.s

.PHONY : responsive_label.s

# target to generate assembly for a file
responsive_label.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_label.cpp.s
.PHONY : responsive_label.cpp.s

responsive_layout.o: responsive_layout.cpp.o

.PHONY : responsive_layout.o

# target to build an object file
responsive_layout.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_layout.cpp.o
.PHONY : responsive_layout.cpp.o

responsive_layout.i: responsive_layout.cpp.i

.PHONY : responsive_layout.i

# target to preprocess a source file
responsive_layout.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_layout.cpp.i
.PHONY : responsive_layout.cpp.i

responsive_layout.s: responsive_layout.cpp.s

.PHONY : responsive_layout.s

# target to generate assembly for a file
responsive_layout.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_layout.cpp.s
.PHONY : responsive_layout.cpp.s

responsive_window.o: responsive_window.cpp.o

.PHONY : responsive_window.o

# target to build an object file
responsive_window.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_window.cpp.o
.PHONY : responsive_window.cpp.o

responsive_window.i: responsive_window.cpp.i

.PHONY : responsive_window.i

# target to preprocess a source file
responsive_window.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_window.cpp.i
.PHONY : responsive_window.cpp.i

responsive_window.s: responsive_window.cpp.s

.PHONY : responsive_window.s

# target to generate assembly for a file
responsive_window.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/responsive_window.cpp.s
.PHONY : responsive_window.cpp.s

screenshot.o: screenshot.cpp.o

.PHONY : screenshot.o

# target to build an object file
screenshot.cpp.o:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/screenshot.cpp.o
.PHONY : screenshot.cpp.o

screenshot.i: screenshot.cpp.i

.PHONY : screenshot.i

# target to preprocess a source file
screenshot.cpp.i:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/screenshot.cpp.i
.PHONY : screenshot.cpp.i

screenshot.s: screenshot.cpp.s

.PHONY : screenshot.s

# target to generate assembly for a file
screenshot.cpp.s:
	$(MAKE) -f CMakeFiles/cw2.dir/build.make CMakeFiles/cw2.dir/screenshot.cpp.s
.PHONY : screenshot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cw2"
	@echo "... edit_cache"
	@echo "... cw2_autogen"
	@echo "... cw2_autogen/mocs_compilation.o"
	@echo "... cw2_autogen/mocs_compilation.i"
	@echo "... cw2_autogen/mocs_compilation.s"
	@echo "... responsive_label.o"
	@echo "... responsive_label.i"
	@echo "... responsive_label.s"
	@echo "... responsive_layout.o"
	@echo "... responsive_layout.i"
	@echo "... responsive_layout.s"
	@echo "... responsive_window.o"
	@echo "... responsive_window.i"
	@echo "... responsive_window.s"
	@echo "... screenshot.o"
	@echo "... screenshot.i"
	@echo "... screenshot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

