//
// Created by twak on 14/10/2019.
//

#include "responsive_window.h"
#include "responsive_layout.h"
#include "screenshot.h"
#include <iostream>
#include <QApplication>
#include <QMediaPlayer>
#include <QtWidgets/QGraphicsScene>
#include <QtMultimediaWidgets/QGraphicsVideoItem>
#include <QtMultimediaWidgets/QVideoWidget>
#include <QMediaPlaylist>


ResponsiveWindow::ResponsiveWindow() {

    setWindowTitle("2811: Coursework 1");
    setMinimumSize(320, 320);

    createWidgets();
}

void ResponsiveWindow::createWidgets() {

    ResponsiveLayout * rl = new ResponsiveLayout();

    // add all the widgets we need to demonstrate all layouts
    rl->addWidget(new ResponsiveLabel(kNavTabs));
    rl->addWidget(new ResponsiveLabel(kSearchButton));
    // we might have more than one search results
    rl->addWidget(new ResponsiveLabel(kSearchResult));
    rl->addWidget(new ResponsiveLabel(kSearchResult));
    // note that later widgets are drawn on top of earlier widgets

    setLayout(rl);
}

// please DO NOT edit this file beyond this line
int main(int argc, char *argv[]) {

    // let's just check that Qt is operational first
    cout << "Qt version: " << QT_VERSION_STR << endl;

    QString fileName = "/media/twak/data/pics/contour/new phone 2_to_merge/MOV_0022.mp4";
    // create the Qt Application
    QApplication app(argc, argv);

    QMediaPlayer* player = new QMediaPlayer;

    QMediaPlaylist* playlist = new QMediaPlaylist(player);
//    playlist->addMedia(QUrl::fromLocalFile("/media/twak/data/pics/contour/new phone 2_to_merge/MOV_0022.mp4"));
    player->setMedia(QUrl::fromLocalFile("/media/twak/data/pics/contour/ed_fishing_lakes/MP_ROOT/100ANV01/MAH00285.MP4"));
//    playlist->addMedia(QUrl("file:///media/twak/data/pics/contour/new phone 2_to_merge/MOV_002xx2.mp4"));
//    playlist->addMedia(QUrl("http://example.com/myclip2.mp4"));

    QVideoWidget* videoWidget = new QVideoWidget;
    player->setVideoOutput(videoWidget);

    videoWidget->show();
//    playlist->setCurrentIndex(0);
    player->play();


//    QWidget window;
//    QHBoxLayout* hb = new QHBoxLayout();
//    hb -> addWidget(mediaPlayer);
//    window.setLayout(hb);
//    window.show();
        // wait for the app to terminate
        return app.exec();
    }

//        // interactive mode - run the regular superclass
//        ResponsiveWindow window;
//        window.show();
//        // wait for the app to terminate
//        return app.exec();
//}

